name: Run Pre commit-hook
on:
  pull_request:
    branches: [main]
jobs:
  pre-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: hashicorp/setup-terraform@v3
      - uses: pre-commit/action@v3.0.0
